### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#1]
autoupdate handle by jmmserver

/api/webui/update - will start the process
/api/webui/latest - will return latest version

**Comment by bigretromike** [comment]
https://github.com/bigretromike/jmmserver/commit/b65a73699857eab426bccb79394a370a7e8ff91c

**Comment by bigretromike** [comment]
This is now live and working

**Comment by hidden4003** [comment]
Supported starting from 0.1.2 https://github.com/japanesemediamanager/jmmserver-webui/commit/0d05e24a95e26a842dfb811b3fdd7701d30209d0
