### ISSUE TITLE
Update process

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#13]
As the update now detects and redirects, after the initial redirect to login screen (which has cached version as you said before) you are unable to login without refreshing it manually. (0.1.4 -> 0.1.5)

**Comment by hidden4003** [comment]
Fixed in https://github.com/japanesemediamanager/jmmserver-webui/commit/51c81ab78930cfcfe12067be1f2a64b345c649d6 (not released yet) so will only work normally when updating from 0.1.6+  to a newer version.
