### ISSUE TITLE
Change between unstable and stable

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#17]
Ability to pick in settings which version you want to install (stable or unstable)
From https://developer.github.com/v3/repos/releases/ I only see that there is latest or GET /repos/:owner/:repo/releases/tags/:tag  
so the unstable would have to have same tag - which is possible.

This could end up usefull for testing things as it would be easier than downloading and replacing things on remote hosts.

What do you think ?

**Comment by ElementalCrisis** [comment]
Agreed, would be a good way to get people to help test upcoming features. Just need to make sure we indicate somewhere, probably in the version number that it's a beta.

**Comment by bigretromike** [comment]
as you switch channel if channel is "dev" or "unstable" it should add "-dev" to end of version

**Comment by hidden4003** [comment]
I don't really understand how it would work, latest always gives latest release and only other way is to check full list or search by known tag.

**Comment by bigretromike** [comment]
use only one and same tag for "dev" version. You create new dev version after deleting old. or if you want so much have multiply version then name them like latest version + dev so it can be taken out /latest/ + dev

**Comment by hidden4003** [comment]
you can only assign one tag to release, so I don't think you can have a release tagged both dev and version number, you can put 2 tags on a commit but only one of them will be linked to release.
Can't we just use pre-release flag? so ui sees latest release is different but if user in stable channel and release is not stable not show button and that's it, version can be whatever as I just compare it, so I would prefer dev version to be a short commit hash (a342df) rather than 0.1.5-dev.

**Comment by bigretromike** [comment]
that wouldnt work.
ex. current version 2.0, pre version 2.1-dev, user version: 1.0. User check /latest/ see 2.1-dev but as its not stable it wont update... as latest return only latest version, no matter if pre/final

**Comment by bigretromike** [comment]
or just use master branch with dev.zip in builld and the update button would allways work. dunno

**Comment by ElementalCrisis** [comment]
What about an option that when checked changes the location to a new folder on the repo with the dev build?

**Comment by hidden4003** [comment]
Fixed server side and made changes to Web UI so updates for stable with attached files will work starting  with 0.1.8 earlier versions are stuck now since API was changed.

**Comment by hidden4003** [comment]
0.1.8 build was broken and I didn't notice, fixed in 0.1.9

**Comment by hidden4003** [comment]
Added a setting to switch channel in 0.3.0-dev
