### ISSUE TITLE
Escaped Character Issue

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#20]
![firefox_2016-08-12_04-05-36](https://cloud.githubusercontent.com/assets/9443295/17620555/0f8e8232-6042-11e6-8930-b769e902b8b3.png)

We had a similar problem in JMM Desktop, here's how I fixed it. 

https://github.com/japanesemediamanager/jmmclient/pull/363/commits/de80ba992646452cb9073fb3ef175ab44a2c0fe7

**Comment by hidden4003** [comment]
As I consume JSON that does not need html escaping, I would prefer for this to be solved server-side.

**Comment by bigretromike** [comment]
fix'd : https://github.com/bigretromike/jmmserver/commit/fee7c997390b97d30ca5b00b975ba10dd3720af3
