### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/jmmserver-webui#21]
It is possible to use Travis CI to make release builds automatically, all that is needed is some configuration and when commit gets tagged it will automatically create a release. The difference is that the resulting file will have to be downloaded from release assets and not from the repository itself.

**Comment by bigretromike** [comment]
Not a problem. Make one and I will make api update for it.

**Comment by hidden4003** [comment]
Should work ok with normal releases. Unstable ones is still a problem it doesn't work if you try to reuse a tag.

**Comment by hidden4003** [comment]
Done in 85d486389060df1f71c269b54cd5d1878a6cfb48
