### ISSUE TITLE
webui version

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#3]
should be visible on main panel, or there should be menu from drop down user menu "about" and there should be version.

One or both options

**Comment by ElementalCrisis** [comment]
If you take a look at the mock-up, I put the version number on the bottom bar in the middle.

**Comment by hidden4003** [comment]
Added by https://github.com/japanesemediamanager/jmmserver-webui/commit/7825cc48c36fcc2d15bac477534c6552a1d324c8
