### ISSUE TITLE
Files And Series Count Remains At 0

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#30]
![firefox_2016-08-14_21-23-50](https://cloud.githubusercontent.com/assets/9443295/17655838/c18cc9b8-6267-11e6-8089-1f46e5aab71a.png)

Version 0.1.9

**Comment by hidden4003** [comment]
I broke it again with reducers refactor ;)

**Comment by hidden4003** [comment]
Should be fixed in 0.1.10-dev2
