### ISSUE TITLE
Center Profile Button

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#32]
![firefox_2016-08-13_17-10-54](https://cloud.githubusercontent.com/assets/9443295/17662731/9ec08a2a-629c-11e6-8ded-b66c6c24e15a.png)

**Comment by hidden4003** [comment]
Fixed in current dev

**Comment by hidden4003** [comment]
Should be fixed in 0.1.10-dev2

**Comment by bigretromike** [comment]
was "update" button linked to update/unstable now ?

**Comment by hidden4003** [comment]
Update button is linked to stable.
