### ISSUE TITLE
Import Folder add/edit/delete popup

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/jmmserver-webui#36]
![import_popup_2](https://cloud.githubusercontent.com/assets/197087/17693052/ba566fde-63a5-11e6-9cd8-028d93d7691d.png)
![import_popup_3](https://cloud.githubusercontent.com/assets/197087/17693051/ba5656a2-63a5-11e6-9bcb-393ce9c46712.png)
![import_popup_4](https://cloud.githubusercontent.com/assets/197087/17693053/ba614896-63a5-11e6-8161-83956b0b2c8e.png)
- [x] API call to edit a folder (@bigretromike)
- [x] API call to get directory tree/ subtree from server for Explore button (@bigretromike)
- [x] Create popup with tabs? 
- [x] Create and connect add new folder tab
- [ ] Create and connect edit/delete folder tab
- [ ] Create and connect providers tab (might postpone that until merge with cloud branch)

**Comment by hidden4003** [comment]
So what do you think of edit? Another popup on top of this one, or just the name transforming into text field with browse button?

**Comment by ElementalCrisis** [comment]
In my mind, clicking edit takes the user back to the New tab with that import folders info populated.

**Comment by bigretromike** [comment]
"API call to get directory tree/ subtree from server for Explore button" its not inside jmm right?! You want api that return directories of what ? system drivers ?

**Comment by bigretromike** [comment]
wont it be better to add button that explore drivers? like "upload" button make you pick your local drivers?

**Comment by hidden4003** [comment]
In 50% of the cases jmm will be on the remote server, so browsing the pc/mobile that the browser is running on is pointless. At least in my dev setup jmm is running on different pc that the one I develop and test webui.

**Comment by bigretromike** [comment]
But thats how jmmd works, right ?

On August 17, 2016 9:42:04 AM GMT+02:00, hidden4003 <notifications@github.com> wrote:
>In 50% of the cases jmm will be on the remote server, so browsing the
>pc/mobile that the browser is running on is pointless. At least in my
>dev setup jmm is running on different pc that the one I develop and
>test webui.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver-webui/issues/36#issuecomment-240337498

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hidden4003** [comment]
Web UI is not jmmd and in 3.6.0.1 streaming was added that allows server and client to be on different machines, so we can no longer assume that folder is local to the client. We have to always assume that Web UI is running on a different machine than the server, and if the provider is cloud even the browse button you suggested wouldn't work. 
That shouldn't be a problem, server already has that code (at least for cloud), you just have hook it up to an API call, with normal folder you just give me the current folder then I send another API request  with subfolder, so you don't have to send whole tree at once.

**Comment by bigretromike** [comment]
but nancy don't have cloud path merged in...

also:
How do I add my local drivers as input folder if server is in cloud ?!

**Comment by hidden4003** [comment]
You select provider : local, cloud we will add as soon as 3.6 releases and cloud is merged to master, then we merge master to nancy. For now I need a call to return a list of folders in a directory.

**Comment by bigretromike** [comment]
I select provider: local, but webui which runs on remote server dont have access to my local drivers.. right...
so i could only add locals (of server) or cloud or nas that have access to server.

**Comment by bigretromike** [comment]
remamber no matter WHERE webui runs the JMMServer need access to files, so if its run on remote host you can't list your locals driver if they not sheared

**Comment by bigretromike** [comment]
and why would you need folders from import folder anyway ? you have those in recently added files.

**Comment by hidden4003** [comment]
Web UI IS the server, so all paths have to be RELATIVE to the SERVER, your client paths are useless to a server, therefore I need an API function to browse local/cloud folder tree using the server.

**Comment by bigretromike** [comment]
/folder/edit added, provide ImportFolder structure with ID to edit it.

**Comment by bigretromike** [comment]
Also:
> We have to always assume that Web UI is running on a different machine than the server
and now you saying that you want local (for server) directories.

Im not sure why you want to handle browser button function inside jmmserver but will make one in few minutes

**Comment by bigretromike** [comment]
GET /os/folder/base
POST /os/folder/ BODY: OSFolder essential is "full_path"
GET /os/drives

Sorry but I dont have time to update wiki to make those infos there
