### ISSUE TITLE
Interactive Log

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#37]
Two different ideas. The top one uses a pop-up to show the different filter options and general log options while the bottom one has it's own row for them.

![interactive log - mockup](https://cloud.githubusercontent.com/assets/9443295/17693773/931695d4-6355-11e6-8b0c-2e895b37b952.png)

![interactive log - mockup v2](https://cloud.githubusercontent.com/assets/9443295/17693842/d0f5631c-6355-11e6-8517-832061bd3b93.png)

In terms of the actual filter options and log options, the ones I put are just temporary. We can decide on the actual ones later as well as what else we need to add.

**Comment by hidden4003** [comment]
I was thinking of something like this, using bootstrap so it would look much better.
![clipboard01](https://cloud.githubusercontent.com/assets/197087/17695578/de4723dc-63b1-11e6-8cfe-1e18d31d5c7e.jpg)

**Comment by bigretromike** [comment]
@hidden4003 I like the bootstrap idea, as the @ElementalCrisis is classic and less flexible

**Comment by ElementalCrisis** [comment]
Works for me, we'll still need a section for log options but that can have it's own row.

**Comment by bigretromike** [comment]
This is probably relevant but dont resolve all the mockup things: https://github.com/japanesemediamanager/jmmserver-webui/issues/60
