### ISSUE TITLE
Settings Tab

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#39]
![settings - mockup](https://cloud.githubusercontent.com/assets/9443295/17697002/fe217734-6366-11e6-8779-e0209e21e80d.png)

Its a work in progress but should provide the general idea, The settings page is anything related to JMM Server so there should be a box for Database setup/info and general JMM Server settings as well.

Also what do you guys think about the yes/no and daily/weekly/monthly switches?

**Comment by bigretromike** [comment]
Why do we need counter at settings ? 
log rotation aint there even... but daily/weekly/montly is ok.
but the light/dark switch.... Can we make it instead of on/off make it light/dark ?

**Comment by ElementalCrisis** [comment]
- The counter is global, it's on every tab and gives substance to each tab.
- Log rotation will be available when the Web UI is launched as both are apart of 3.7, 
- I just separated them so each style had its own button.

**Comment by bigretromike** [comment]
why not drop down box for styles ? dark/light/custom... if we support multiply custom skins...  then name of custom

**Comment by ElementalCrisis** [comment]
From what we were talking about, we can only do a light/dark and one custom style.

**Comment by hidden4003** [comment]
well there is no limit on style themes really but I didn't make any support for them yet

**Comment by ElementalCrisis** [comment]
If thats the case I've got an idea on a better way to handle skin selecting, I'll create a mockup for it later.

**Comment by hidden4003** [comment]
I merged a page with buttons, not working yet. Is there an API where web ui can store settings?
The log part is not web ui specific but still probably no api for that.

**Comment by ElementalCrisis** [comment]
Updated mockup with database setup pop-up. 
![settings - mockup v2](https://cloud.githubusercontent.com/assets/9443295/17831421/e8d8bc50-669c-11e6-8e81-0e83033d1c9b.png)

![database setup](https://cloud.githubusercontent.com/assets/9443295/17831422/f09ef666-669c-11e6-976c-7054895abb32.png)

Options reflect current options for database so SQL Server will look similar but will select the server address with a refresh button next to it.

**Comment by bigretromike** [comment]
we already have lock "FirstRun" for wizard, are we reusing this one or we want another lock?

**Comment by ElementalCrisis** [comment]
Here's the idead @hidden4003 and I came up with. 

We'll need another one as down the road, when the user first launches the Web UI we'll need to use a temporary full access account to create the database and their actual user account. Once down and to prevent unauthorized access we'll lock this super account that is only unlockable by editing the .config file in the JMM Server folder.

**Comment by bigretromike** [comment]
hmmm... isint it a backdoor then? 
current solution give you "full" access to create database, but you arent able to do anything to that database later on even with that "full access" thing.

The idea is ok, as you can hardcoded that account and flag it as "locked" with tweak of structure that holds the account UserDatabase, but what is the benefit over current implementation ?

**Comment by ElementalCrisis** [comment]
The issue I see is a user changing a DB setting that causes them DB to not load, for example accidentally changing it from SQLite to MySQL. How are they going to be able to login and fix this if the user account is stored in the database they can no longer access?

The method describe above solves that, just like how routers reset the admin account. Normally you could just edit the database type in the config file but from my understanding aren't we moving away from storing that info in a text file?

**Comment by bigretromike** [comment]
easy: firstrun = true

**Comment by bigretromike** [comment]
so you have access to db_setup again

**Comment by bigretromike** [comment]
but its not same like in routers because you dont wipe database when you reset

**Comment by ElementalCrisis** [comment]
I'm going to revisit the settings section, it will probably be best to have sub-tabs in settings as there will be too many boxes if all in one section. Off the top of my head we'll need one for Community sites with their various options, AniDB and it's options, a general settings one and an image settings one.

**Comment by bigretromike** [comment]
Still the latest mockup dont include slider with light/dark/custom we dont need 3seperate buttons for same functionality

**Comment by ElementalCrisis** [comment]
Updated Style Options settings.

![settings - web ui](https://cloud.githubusercontent.com/assets/9443295/18579683/08daedb0-7bac-11e6-8dc3-9e763d76475f.png)

**Comment by bigretromike** [comment]
looking NICE ! good work

**Comment by hidden4003** [comment]
To start working on this I need API to get/save settings.

**Comment by bigretromike** [comment]
And API need jmm to support it ;-)

**Comment by bigretromike** [comment]
Api for saving settings was added - can we close this ?

**Comment by ElementalCrisis** [comment]
Yeah, we can create individual issues for the settings we need to add still.
