### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/jmmserver-webui#5]
![dashboard_-_remaining_items_v2](https://cloud.githubusercontent.com/assets/197087/17522961/9ccced7e-5e61-11e6-9246-777557df72de.png)
- [x] 1. Recent Files should only show the past 6 added files. We can have it as a user setting in a future update. Similar to the commands box, there is a button on the right that when click takes the user to the Interactive Log, have it hidden for now until Interactive log is added.
- [x] 2. We should show the import status for each file, the green success if the file was imported sucessfully and the red error if the file was not imported successfully
- [x] 3. Queued Commands does not update nor show total amount of queued commands.
- [x] 4. The top nav bar is missing the notifications indicator (Bell Icon) which can be clicked to show the last 10 notifications in a drop down. It's also missing the user box, should show the logged in user with a couple options like "Change Password" and Logout for now. Also included is the search icon that when click opens the search bar, we should add it but have it hidden by default until later.
- [x] 5. Text in the Commands box should be trimmed so it doesn't extend box. Can be a setting in a future update. 
- [x] 6.The footer bar should be added and shown at the bottom of the page, the text in the middle shows the application name and version number with the scroll to top button on the far right.
- [x] 7.Implement the JMM News section, shows the article title and when clicked takes the user to that article. Similar to the commands box, there is a button on the right that when click takes the user to the blog so they can read more.
- [x] 8. Import Folders should be named Import Folders Overview. Also using it as an example each box should have a subtitle with it, check original mockup for the subtitle.Similar to the commands box, there is a button on the right that when click takes the user to the Add import Folder modal, have it hidden for now until Interactive log is added
- [x] 9. The Run Import button need to be pushed up as it's resting on the line.
- [x] 10. Quick Actions needs to be implamented, pick 6 commands for default, we will allow users to select actions in a future update.Similar to the commands box, there is a button on the right that when click takes the user to the Quick Actions section in settings, have it hidden for now until Interactive log is added.
- [x] 11. In the bottom-right we have three quick links, Home takes the user to the website, GitHub takes the user to GitHub and Support takes them the support page. Use fake URL's for now.
- [x] 12. Add collapsible menu button on the left-side of JMM Server.

**Comment by ElementalCrisis** [comment]
Drop Down Mockup.

![dashboard mockup v2 - drop down](https://cloud.githubusercontent.com/assets/9443295/17523911/26d938de-5e11-11e6-9d5a-1723f2e8fb53.png)

**Comment by bigretromike** [comment]
for 7. https://github.com/japanesemediamanager/jmmserver/pull/361

**Comment by bigretromike** [comment]
for 2: https://github.com/japanesemediamanager/jmmserver/issues/362

**Comment by bigretromike** [comment]
addon for 6: please make color same as background so it wont look like frame or just throw that away and add it at bottom of page.

**Comment by ElementalCrisis** [comment]
Remember, item 6 refers to the footer which is shown at the bottom of the page. In the mockup the end of the page is visible so you can see the footer. Longer pages will obviously not show the footer until the user has scrolled down far enough to see it.
