### ISSUE TITLE
Implement Passwords

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver-webui#51]
Currently only the username is needed to login.

**Comment by bigretromike** [comment]
no ?
did you setup password for default user ?its empty by default

**Comment by ElementalCrisis** [comment]
I did, but just did a test and it seems JMM Desktop doesn't save the password you've inputted.

**Comment by bigretromike** [comment]
api can change your password also, and it should work by now ;-) that need to be added to webui

**Comment by bigretromike** [comment]
so this is working on webui but not on jmmclient so we could close this here as you can easly change/set password with api and use it to login

**Comment by ElementalCrisis** [comment]
Yeah @hidden4003 fixed the Web UI issues and @rickdb fixed it on Server.
