### ISSUE TITLE
Update button - showing up

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver-webui#8]
Currently latest is 0.1.2. that is the version I have and it still show me the button

**Comment by bigretromike** [comment]
Also it dosn't work, or it dosn't refresh pages. nothing happens when you click it

**Comment by hidden4003** [comment]
Did not see this behavior in 0.1.3, update worked, but no refresh or message after successful update

**Comment by bigretromike** [comment]
Clicking it make it update but because you don't refresh it the button stay there and looks like it don't work.
Also 0.1.3 have version number of 0.1.2 so maybe thats why the button is there

**Comment by hidden4003** [comment]
Better now, redirect to login works but it shows cached version so manual refresh is needed.

**Comment by bigretromike** [comment]
cant you somehow add header with that would store that value and if header is missing use local version(cached) if not then use that version ? 
or remove it from login screen ? as it would confuse.. people after update ..
or make note issue with "knows issues" that wont be fixed currently but are acknowledge for later iterations

**Comment by bigretromike** [comment]
Also it does not refresh after update or does it only work post 0.1.4 ?:-) so upgrade from 0.1.3 > 0.1.4 wont trigger this ?

**Comment by hidden4003** [comment]
There is some issue with the way it works, since it uses browser history api it causes it to use cached version of the page when I redirect back.
Thinking of it I could just force refresh of current page that should kick user back to login.

**Comment by hidden4003** [comment]
Should be fixed in https://github.com/japanesemediamanager/jmmserver-webui/commit/51c81ab78930cfcfe12067be1f2a64b345c649d6
